In [1]:
import pydisagg
from pydisagg.disaggregate import split_datapoint
import numpy as np
from pydisagg.models import RateMultiplicativeModel
from pydisagg.models import LMO_model
from pydisagg.models import LogOdds_model
import pandas as pd

In [2]:
populations=np.array([20,10,5])
rate_pattern=np.array([0.1,0.5,0.7])
observed_total=31
observed_total_SE=2.5

cov_scalar=0.1

covariance_matrix=cov_scalar*np.array([
    [3,-1,-1],
    [-1,3,-1],
    [-1,-1,3]
])

In [3]:
model=RateMultiplicativeModel(rate_pattern=rate_pattern)

In [4]:
model.fit_beta(
    populations,
    observed_total=observed_total,
    observed_total_se=observed_total_SE,
    )

In [5]:
beta=model._compute_beta(populations,observed_total,rate_pattern)
beta

1.0826119473216687

In [6]:
grad_result=model._fgrad_H(beta,populations,rate_pattern)
grad_result

T Diff at rate pattern [10.          2.          1.42857143]
Bucket populations [20 10  5]
Denominator [-0.81969017  2.56762636  1.37753   ]


array([59.04761905, 29.52380952, 14.76190476])

In [7]:
model.T(rate_pattern)+model.beta_parameter

array([-1.21997315,  0.38946477,  0.725937  ])

In [8]:
1/model.T_diff(-1.21997315)

-1.21997315

In [11]:
h=0.01


r1=rate_pattern+h*np.identity(3)[0]
r2=rate_pattern-h*np.identity(3)[0]

model.rate_pattern=r1
H1=model._H_func(beta,populations)
model.rate_pattern=r2
H2=model._H_func(beta,populations)


result=(H1-H2)/(2*h)
result

59.04761904761919

In [12]:
result/grad_result[1]

2.000000000000005

In [13]:
result/grad_result[0]

1.000000000000002

In [14]:
(model._H_func(beta+h,populations)-model._H_func(beta-h,populations))/(2*h)

30.410030637455066

In [15]:
model._H_diff(beta,populations)

30.40952380952381

In [16]:
b1=model._compute_beta(populations,observed_total,rate_pattern+h*np.identity(3)[0])
b2=model._compute_beta(populations,observed_total,rate_pattern-h*np.identity(3)[0])

(b1-b2)/(2*h)

-1.9049923116135292

In [9]:
model._build_parameter_covariance(model.beta_parameter,populations,rate_pattern,covariance_matrix,observed_total_SE)

array([[ 0.00650364, -2.40309176,  0.84573307,  0.81213267],
       [-2.40309176,  0.3       , -0.1       , -0.1       ],
       [ 0.84573307, -0.1       ,  0.3       , -0.1       ],
       [ 0.81213267, -0.1       , -0.1       ,  0.3       ]])

In [17]:
model._fgrad_Hinv(model.beta_parameter,populations,rate_pattern)

T Diff at rate pattern [10.          2.          1.42857143]
Bucket populations [20 10  5]
Denominator [-0.81969017  2.56762636  1.37753   ]


array([1.9047619 , 0.95238095, 0.47619048])

In [14]:
model._H_func(model.beta_parameter,populations)

31.000000000000007

In [38]:

h=0.02

model.rate_pattern=rate_pattern
f1=model.fit_beta

model.rate_pattern=rate_pattern + h*np.identity(3)[0]


array([0.1 , 0.49, 0.7 ])

In [35]:
(p_right-p_left)/(2*h)

-0.9524097485347327

In [33]:
p_right-p_left

-0.038099846232270584

In [40]:
model.beta_parameter

1.0921813983378192