In [1]:
import importlib
import pydisagg

importlib.reload(pydisagg)


from pydisagg.disaggregate import split_datapoint
import numpy as np
from pydisagg.models import RateMultiplicativeModel
from pydisagg.models import LMO_model
from pydisagg.models import LogOdds_model
import pandas as pd

In [6]:
populations=np.array([20,10,5])
rate_pattern=np.array([0.1,0.5,0.7])
observed_total=31
observed_total_SE=2.5

cov_scalar=0.1

covariance_matrix=cov_scalar*np.array([
    [3,-1,-1],
    [-1,3,-1],
    [-1,-1,3]
])

In [7]:
model=RateMultiplicativeModel(rate_pattern=rate_pattern)

In [8]:
model.fit_beta(
    populations,
    observed_total=observed_total,
    observed_total_se=observed_total_SE,
    )

In [9]:
model._build_parameter_covariance(model.beta_parameter,populations,rate_pattern,covariance_matrix,observed_total_SE)

array([[ 0.00650364, -2.40309176,  0.84573307,  0.81213267],
       [-2.40309176,  0.3       , -0.1       , -0.1       ],
       [ 0.84573307, -0.1       ,  0.3       , -0.1       ],
       [ 0.81213267, -0.1       , -0.1       ,  0.3       ]])

In [10]:
model._fgrad_Hinv(model.beta_parameter,populations,rate_pattern)

array([-7.87079449,  0.25126759,  0.16726659])

In [14]:
model._H_func(model.beta_parameter,populations)

31.000000000000007

In [38]:

h=0.02

model.rate_pattern=rate_pattern
f1=model.fit_beta

model.rate_pattern=rate_pattern + h*np.identity(3)[0]


array([0.1 , 0.49, 0.7 ])

In [35]:
(p_right-p_left)/(2*h)

-0.9524097485347327

In [33]:
p_right-p_left

-0.038099846232270584