In [1]:
from pydisagg.disaggregate import split_datapoint
import numpy as np
from pydisagg.models import RateMultiplicativeModel
from pydisagg.models import LMO_model
from pydisagg.models import LogOdds_model
import pandas as pd

### Basic example using RateMultiplicativeModel and OddsMultiplicativeModel

In [2]:
populations=np.array([20,10,5])
rate_pattern=np.array([0.1,0.5,0.7])
observed_total=31.
observed_total_SE=2.5

In [3]:
rmm=RateMultiplicativeModel()
oddm=LogOdds_model()

In [4]:
print(oddm.fit_beta(observed_total,rate_pattern,populations))
print(rmm.fit_beta(observed_total,rate_pattern,populations))

3.679899347162453
1.0826119473216687


In [5]:
print(rmm.split_to_rates(observed_total,rate_pattern,populations))
print(oddm.split_to_rates(observed_total,rate_pattern,populations))

[0.2952381  1.47619048 2.06666667]
[0.81497625 0.97539516 0.98930469]


In [6]:
b=rmm.fit_beta(observed_total,populations,rate_pattern)

bse=rmm.beta_standard_error(
    b,
    populations,
    rate_pattern,
    observed_total_SE
)
print(bse)
print(bse * rmm.count_diff_beta(b,rate_pattern,populations))
print(np.sum(bse * rmm.count_diff_beta(b,rate_pattern,populations)))

0.08064516129032258
[0.47619048 1.19047619 0.83333333]
2.5


In [7]:
rmm.count_split_standard_errors(b,rate_pattern,populations,observed_total_SE)

array([0.47619048, 1.19047619, 0.83333333])

In [9]:
oddm.split_to_rates(observed_total,rate_pattern,populations)

array([0.81497625, 0.97539516, 0.98930469])

In [10]:
oddm.fit_beta(observed_total,rate_pattern,populations)

3.679899347162453

In [11]:
b=oddm.fit_beta(observed_total,rate_pattern,populations)

In [12]:
1/oddm.H_diff_beta(b,rate_pattern,populations)

0.30223366091526715

In [16]:
oddm.beta_standard_error(
    b,
    rate_pattern,
    populations,
    observed_total_SE
)

0.7555841522881679

In [22]:
pattern_cov=(np.ones((3,3))+np.identity(3)*2)*0.1

In [23]:
oddm.parameter_covariance(b,rate_pattern,populations,observed_total_SE,pattern_cov)

array([[0.75558415, 3.07488133, 1.10740652, 1.06460714],
       [3.07488133, 0.3       , 0.1       , 0.1       ],
       [1.10740652, 0.1       , 0.3       , 0.1       ],
       [1.06460714, 0.1       , 0.1       , 0.3       ]])